
library(MASS)
library(jtools)
library(dplyr)
library(boot)
library(tidyverse)
library(texreg)
library(ggplot2)
library(knitr)
library(lfe)
library(corrplot)
library(patchwork)
library(reshape)
library(styler)
library(spatstat)
library(sjmisc)
library(stringr)
library(forcats)
library(latex2exp)
library(figpatch)
library(khroma)
library(hrbrthemes)
library(gridExtra)

setwd('~/OneDrive - Northeastern University/neu/rezoning-schools/analysis/')
opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)